command_timeout = 10000

[docker_context]
disabled = true

[character]
success_symbol = "âœ¨"
error_symbol = "ğŸ’¥"

[gcloud]
disabled = true

[git_branch]
symbol = ":"
format = "[on](italic) [$symbol$branch]($style) "

[git_state]
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
ahead = '[â†‘$count](green)'
behind = '[â†“$count](red)'
diverged = '[â†‘$ahead_count](green) [â†“$behind_count](red)'
untracked = "?"
stashed = "ğŸ“¦"
modified = '[ğŸ“\($count\)](yellow) '
staged = '[+\($count\)](green)'
